<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableSdkContainerSupport>true</EnableSdkContainerSupport>
    <ContainerBaseImage>mcr.microsoft.com/dotnet/aspnet:10.0</ContainerBaseImage>
    <UserSecretsId>ab332951-b88c-4a4a-b167-87526210541e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ContainerPort Include="8080" Type="tcp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MWDashboard.Shared\MWDashboard.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Common\ApiDocsExtensions.cs" Link="ApiDocsExtensions.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.OpenApi" Version="3.9.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.18" />
  </ItemGroup>

</Project>
